# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise32"
  config.vm.provision :shell, :path => "bootstrap.sh"

  # Web Server
  config.vm.network "forwarded_port", guest: 3000, host: 13000

  # MongoDB
  config.vm.network "forwarded_port", guest: 27017, host: 37017

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--memory", "613"]
  end

end

