# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "Centos-6.5"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.5.1/centos65-x86_64-20131205.box"

  config.vm.provision :shell, :path => "bootstrap.sh"
  
  config.vm.network "forwarded_port", guest: 8080, host: 18080
  config.vm.synced_folder "../../workspace", "/workspace"

  config.vm.provider :virtualbox do |vb|
    vb.name = "Centos-Docker"
    vb.gui = false
    vb.customize ["modifyvm", :id, "--memory", "2048"]
  end
end

